# Generated by Django 3.2 on 2022-06-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20220601_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
